#! /bin/sh -e
export export BOOTUUID=`uuidgen`
export export DATANAME='data'
export export DATAUUID=`uuidgen`
export export LUKSDATAUUID=`uuidgen`
export export ARCH='x86_64'
export export MGARELEASE='cauldron'
export export IHTTPD_RPM=`dirname ihttpd-*.${ARCH}.rpm`/`basename ihttpd-*.${ARCH}.rpm`
export export ZONE='Europe/Paris'
export export KEYMAP='fr-latin9'
export export LOCALE='fr_FR.UTF-8'
export export LOCALE_ALT='fr'
export export MAIL='user@example.com'
export export NETHOSTNAME='host.example.com'
export export NETALIAS='host'
export export NETCONFIG=static
export export NETADDRESS4=`printf '192.168.2.%d/24' $[RANDOM%253+2]`
export export NETGATEWAY4='192.168.2.1'
export export NETADDRESS6=`printf 'fd4b:842b:7f35:f1ba::%x/64' $[RANDOM%65534+2]`
export export NETGATEWAY6='fd4b:842b:7f35:f1ba::1'
export export NETDNS='8.8.8.8 8.8.4.4'
export export NETMAC=`printf '%02x:%02x:%02x:%02x:%02x:%02x' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256]`
export export ROOTPASS=`apg -m 32 -x 32 -a 0 -d -n 1`
export export SLASHNAME='slash'
export export SLASHUUID=`uuidgen`
export export LUKSSLASHUUID=`uuidgen`
export export SWAPAUUID=`uuidgen`
export export SWAPBUUID=`uuidgen`
export export USERLOGIN=`apg -M L -a 0 -m 8 -x 8 -d -n 1`
export export USERPASS=`apg -m 32 -x 32 -a 0 -d -n 1`
